import {Activity,BarChart3,Bell,BookOpen,Clock,Flame,Heart,Image,LayoutDashboard,Medal,Settings,Stethoscope,TriangleAlert,UserRound,X,Zap} from 'lucide-react';
import {NavLink,useLocation,useNavigate} from 'react-router-dom';import type {BTKVCase,LabResult,VitalSign} from './types';import {useFavorites,useLearningProgress} from './hooks/storage';
export const disclaimer='BTKV Clinical Challenge is an educational simulation. It is not intended to diagnose patients, determine surgical eligibility, replace institutional protocols, or substitute for supervision by a qualified cardiothoracic and vascular surgeon.';
export function MedicalDisclaimer(){return <aside className="disclaimer"><TriangleAlert size={20}/><div><strong>Educational use only</strong><p>{disclaimer}</p></div></aside>}
const nav=[['LEARNING','/','Dashboard',LayoutDashboard],['LEARNING','/cases','Clinical Cases',Stethoscope],['LEARNING','/cases/heart-pressure','Hemodynamics',Activity],['LEARNING','/cases/crushing-pain/challenge','Daily Drills',Zap],['CLINICAL LAB','/library','References',BookOpen],['CLINICAL LAB','/search','Imaging',Image],['PERFORMANCE','/progress','Progress',BarChart3],['PERFORMANCE','/favorites','Leaderboard',Medal]] as const;
export function Navigation(){return <><aside className="sidebar"><Brand/><div className="nav-status"><i/><span>Training system</span><b>Online</b></div><div className="sidebar-links">{nav.map(([group,to,l,I],index)=>{const label=index===0||group!==nav[index-1][0];return <div className="nav-entry" key={l}>{label&&<small>{group}</small>}<NavLink to={to} end={to==='/' || to==='/cases'}><I size={18}/><span>{l}</span>{l==='Daily Drills'&&<em>3</em>}</NavLink></div>})}</div><div className="sidebar-profile"><div className="level-row"><span>LVL 12</span><b>2,480 XP</b></div><i><u/></i><p><Flame/> 7 day learning streak</p></div><NavLink className="sidebar-settings" to="/settings"><Settings/>Settings</NavLink></aside><nav className="bottom" aria-label="Primary navigation">{nav.filter((_,i)=>[0,1,2,4,6].includes(i)).map(([,to,l,I])=><NavLink to={to} key={l} end={to==='/' || to==='/cases'} aria-label={l}><span className="bottom-icon"><I aria-hidden="true"/></span><span>{l.replace('Clinical ','')}</span></NavLink>)}</nav></>}
export function Brand(){return <div className="brand"><span>BTKV</span><div><b>Clinical Challenge</b><small>Surgical reasoning lab</small></div></div>}
export function Header(){const {pathname}=useLocation();const heart=pathname==='/cases/heart-pressure';const crumbs=heart?['Clinical Cases','Hemodynamics','Heart Pressure']:pathname==='/'?['Command Center','Dashboard']:pathname.split('/').filter(Boolean).map(x=>x.replaceAll('-',' '));return <header><div className="mobile-heading"><span className="brand-mark">B</span><div><small>BTKV LEARNING LAB</small><strong>{crumbs.at(-1)||'Dashboard'}</strong></div></div><nav className="breadcrumbs" aria-label="Breadcrumb">{crumbs.map((x,i)=><span key={x}>{x}{i<crumbs.length-1&&<b>/</b>}</span>)}</nav><div className="header-actions"><span className="header-stat streak"><Flame/> <b>7</b><small>day streak</small></span><span className="header-stat"><Zap/> <b>2,480</b><small>XP</small></span><span className="rank-badge">Rank <b>#12</b></span><NavLink aria-label="Notifications" to="/settings"><Bell/></NavLink><NavLink className="profile-link" aria-label="Information and settings" to="/settings"><UserRound/></NavLink></div></header>}
export function Anatomy({type='heart'}:{type?:string}){return <svg className="anatomy" viewBox="0 0 180 120" role="img" aria-label={`${type} anatomical illustration`}><path d="M90 103C56 80 39 63 44 40c4-19 29-24 46-5 17-19 42-14 46 5 5 23-12 40-46 63Z"/><path d="M91 37c-3-21 8-29 18-29m-7 31c13-17 27-13 31-5M67 36c-9-15-21-14-26-6"/><path className="wave" d="M10 67h35l8-12 8 23 10-38 12 27h87"/></svg>}
export function Badge({children,tone='blue'}:{children:React.ReactNode;tone?:string}){return <span className={`badge ${tone}`}>{children}</span>}
export function CaseCard({item}:{item:BTKVCase}){const [favorites,setFavorites]=useFavorites();const [progress]=useLearningProgress();const saved=favorites.includes(item.id),p=progress[item.id];return <article className="case-card"><div className="thumb"><Anatomy type={item.thumbnail}/><button className={saved?'favorite active':'favorite'} aria-label={saved?'Remove favorite':'Add favorite'} onClick={()=>setFavorites(saved?favorites.filter(x=>x!==item.id):[...favorites,item.id])}><Heart fill={saved?'currentColor':'none'}/></button><Badge tone={item.urgency==='emergency'?'red':'blue'}>{item.urgency}</Badge></div><div className="case-body"><div className="eyebrow">{item.domain} · {item.diagnosisCategory}</div><h3>{item.title}</h3><p>{item.subtitle}</p><div className="meta"><span><Clock/> {item.estimatedMinutes} min</span><Badge tone="gold">{item.difficulty}</Badge></div>{p&&<div className="scoreline"><span>{p.status}</span><b>{p.score}%</b></div>}<NavLink className="button secondary full" to={`/cases/${item.slug}`}>{p?'Continue':'Start Case'}</NavLink></div></article>}
export function VitalSignGrid({items}:{items:VitalSign[]}){return <div className="vitals">{items.map(v=><div className={v.status} key={v.label}><small>{v.label}</small><strong>{v.value}</strong><span>{v.status||'normal'}</span></div>)}</div>}
export function LabResultTable({items}:{items:LabResult[]}){return <div className="table-wrap"><table><thead><tr><th>Test</th><th>Patient</th><th>Reference</th><th>Status</th></tr></thead><tbody>{items.map(x=><tr key={x.name}><td>{x.name}</td><td><b>{x.value}</b> {x.unit}</td><td>{x.reference}</td><td><Badge tone={x.status==='normal'?'teal':x.status==='critical'?'red':'gold'}>{x.status}</Badge></td></tr>)}</tbody></table></div>}
export function EmptyState({title,action}:{title:string;action?:string}){const go=useNavigate();return <div className="empty"><Stethoscope/><h3>{title}</h3><p>Adjust your filters or explore the complete case collection.</p>{action&&<button className="button" onClick={()=>go(action)}>Browse cases</button>}</div>}
export function Modal({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void}){return <div className="modal-bg"><div className="modal" role="dialog" aria-modal="true"><button className="close" onClick={onClose}><X/></button><h2>{title}</h2>{children}</div></div>}
