import {BookOpen,Clock,Heart,Home,LayoutDashboard,Search,Settings,Stethoscope,TriangleAlert,X} from 'lucide-react';
import {NavLink,useNavigate} from 'react-router-dom';import type {BTKVCase,LabResult,VitalSign} from './types';import {useFavorites,useLearningProgress} from './hooks/storage';
export const disclaimer='BTKV Clinical Challenge is an educational simulation. It is not intended to diagnose patients, determine surgical eligibility, replace institutional protocols, or substitute for supervision by a qualified cardiothoracic and vascular surgeon.';
export function MedicalDisclaimer(){return <aside className="disclaimer"><TriangleAlert size={20}/><div><strong>Educational use only</strong><p>{disclaimer}</p></div></aside>}
const nav=[['/','Home',Home],['/cases','Cases',Stethoscope],['/cases/crushing-pain/challenge','Challenge',Heart],['/library','Library',BookOpen],['/progress','Progress',LayoutDashboard]] as const;
export function Navigation(){return <><aside className="sidebar"><Brand/>{nav.map(([to,l,I])=><NavLink to={to} key={l} end={to==='/'}><I size={20}/>{l}</NavLink>)}<NavLink to="/settings"><Settings size={20}/>Settings</NavLink></aside><nav className="bottom">{nav.map(([to,l,I])=><NavLink to={to} key={l} end={to==='/'}><I/><span>{l}</span></NavLink>)}</nav></>}
export function Brand(){return <div className="brand"><span>BTKV</span><div><b>Clinical Challenge</b><small>Surgical reasoning lab</small></div></div>}
export function Header(){return <header><Brand/><div className="header-actions"><NavLink aria-label="Search" to="/search"><Search/></NavLink><NavLink aria-label="Information and settings" to="/settings"><Settings/></NavLink></div></header>}
export function Anatomy({type='heart'}:{type?:string}){return <svg className="anatomy" viewBox="0 0 180 120" role="img" aria-label={`${type} anatomical illustration`}><path d="M90 103C56 80 39 63 44 40c4-19 29-24 46-5 17-19 42-14 46 5 5 23-12 40-46 63Z"/><path d="M91 37c-3-21 8-29 18-29m-7 31c13-17 27-13 31-5M67 36c-9-15-21-14-26-6"/><path className="wave" d="M10 67h35l8-12 8 23 10-38 12 27h87"/></svg>}
export function Badge({children,tone='blue'}:{children:React.ReactNode;tone?:string}){return <span className={`badge ${tone}`}>{children}</span>}
export function CaseCard({item}:{item:BTKVCase}){const [favorites,setFavorites]=useFavorites();const [progress]=useLearningProgress();const saved=favorites.includes(item.id),p=progress[item.id];return <article className="case-card"><div className="thumb"><Anatomy type={item.thumbnail}/><button className={saved?'favorite active':'favorite'} aria-label={saved?'Remove favorite':'Add favorite'} onClick={()=>setFavorites(saved?favorites.filter(x=>x!==item.id):[...favorites,item.id])}><Heart fill={saved?'currentColor':'none'}/></button><Badge tone={item.urgency==='emergency'?'red':'blue'}>{item.urgency}</Badge></div><div className="case-body"><div className="eyebrow">{item.domain} · {item.diagnosisCategory}</div><h3>{item.title}</h3><p>{item.subtitle}</p><div className="meta"><span><Clock/> {item.estimatedMinutes} min</span><Badge tone="gold">{item.difficulty}</Badge></div>{p&&<div className="scoreline"><span>{p.status}</span><b>{p.score}%</b></div>}<NavLink className="button secondary full" to={`/cases/${item.slug}`}>{p?'Continue':'Start Case'}</NavLink></div></article>}
export function VitalSignGrid({items}:{items:VitalSign[]}){return <div className="vitals">{items.map(v=><div className={v.status} key={v.label}><small>{v.label}</small><strong>{v.value}</strong><span>{v.status||'normal'}</span></div>)}</div>}
export function LabResultTable({items}:{items:LabResult[]}){return <div className="table-wrap"><table><thead><tr><th>Test</th><th>Patient</th><th>Reference</th><th>Status</th></tr></thead><tbody>{items.map(x=><tr key={x.name}><td>{x.name}</td><td><b>{x.value}</b> {x.unit}</td><td>{x.reference}</td><td><Badge tone={x.status==='normal'?'teal':x.status==='critical'?'red':'gold'}>{x.status}</Badge></td></tr>)}</tbody></table></div>}
export function EmptyState({title,action}:{title:string;action?:string}){const go=useNavigate();return <div className="empty"><Stethoscope/><h3>{title}</h3><p>Adjust your filters or explore the complete case collection.</p>{action&&<button className="button" onClick={()=>go(action)}>Browse cases</button>}</div>}
export function Modal({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void}){return <div className="modal-bg"><div className="modal" role="dialog" aria-modal="true"><button className="close" onClick={onClose}><X/></button><h2>{title}</h2>{children}</div></div>}
